<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CarDetailsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('car_details')->insert([
            [
                'brand' => 'Porsche',
                'name' => 'Taycan',
                'model' => 'J1',
                'year' => 2021,
                'engine_type' => 'Electric',
                'seat_capacity' => 5,
                'engine_power' => '616 HP',
                'max_speed' => 260,
                'trunk_capacity' => '12 cubic feet',
                'length' => 4963,
                'width' => 1966,
                'height' => 1378,
                'image_url' => 'https://porsche-vietnam.vn/wp-content/uploads/2021/01/j1-taycan-modelimage-sideshot.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand' => 'Peugeot',
                'name' => '3008',
                'model' => 'SUV',
                'year' => 2021,
                'engine_type' => 'Gasoline',
                'seat_capacity' => 5,
                'engine_power' => '165 HP',
                'max_speed' => 200,
                'trunk_capacity' => '19 cubic feet',
                'length' => 4450,
                'width' => 1840,
                'height' => 1620,
                'image_url' => 'https://hcmpeugeot.com/wp-content/uploads/2021/06/PEUGEOT-3008-XAM.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand' => 'Hyundai',
                'name' => 'Custin',
                'model' => 'MPV',
                'year' => 2023,
                'engine_type' => 'Gasoline',
                'seat_capacity' => 7,
                'engine_power' => '170 HP',
                'max_speed' => 190,
                'trunk_capacity' => '20 cubic feet',
                'length' => 4965,
                'width' => 1850,
                'height' => 1720,
                'image_url' => 'https://hyundaingocphat.com.vn/wp-content/uploads/2023/09/hyundai-custin-c-230915.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand' => 'Honda',
                'name' => 'CR-V',
                'model' => 'SUV',
                'year' => 2024,
                'engine_type' => 'Hybrid',
                'seat_capacity' => 5,
                'engine_power' => '204 HP',
                'max_speed' => 190,
                'trunk_capacity' => '17 cubic feet',
                'length' => 4700,
                'width' => 1860,
                'height' => 1680,
                'image_url' => 'https://hondaotovovankiet.vn/wp-content/uploads/2020/03/Honda_CRV_2024_mau_xam_hondaotovovankiet_vn.jpg.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand' => 'Kia',
                'name' => 'Carnival',
                'model' => 'MPV',
                'year' => 2022,
                'engine_type' => 'Gasoline',
                'seat_capacity' => 7,
                'engine_power' => '201 HP',
                'max_speed' => 185,
                'trunk_capacity' => '20 cubic feet',
                'length' => 5155,
                'width' => 1995,
                'height' => 1750,
                'image_url' => 'https://kiavietnam.com.vn/storage/carnival-dosam-1.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand' => 'Peugeot',
                'name' => '408',
                'model' => 'Sedan',
                'year' => 2023,
                'engine_type' => 'Gasoline',
                'seat_capacity' => 5,
                'engine_power' => '168 HP',
                'max_speed' => 210,
                'trunk_capacity' => '16 cubic feet',
                'length' => 4750,
                'width' => 1820,
                'height' => 1470,
                'image_url' => 'https://hcmpeugeot.com/wp-content/uploads/2023/10/2022062701_Peugeot408.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand' => 'Porsche',
                'name' => 'Cayenne',
                'model' => 'SUV',
                'year' => 2023,
                'engine_type' => 'Gasoline',
                'seat_capacity' => 5,
                'engine_power' => '335 HP',
                'max_speed' => 245,
                'trunk_capacity' => '27 cubic feet',
                'length' => 4931,
                'width' => 1983,
                'height' => 1673,
                'image_url' => 'https://porsche-vietnam.vn/wp-content/uploads/2023/04/e3-2nd-cayenne-modelimage-sideshot.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand' => 'Hyundai',
                'name' => 'Santa Fe',
                'model' => 'SUV',
                'year' => 2022,
                'engine_type' => 'Diesel',
                'seat_capacity' => 7,
                'engine_power' => '202 HP',
                'max_speed' => 210,
                'trunk_capacity' => '23 cubic feet',
                'length' => 4785,
                'width' => 1900,
                'height' => 1685,
                'image_url' => 'https://vn-hyundai.com/wp-content/uploads/2018/03/icon-santafe-all-new-vn-hyundai.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand' => 'Kia',
                'name' => 'Sonet',
                'model' => 'SUV',
                'year' => 2024,
                'engine_type' => 'Gasoline',
                'seat_capacity' => 5,
                'engine_power' => '115 HP',
                'max_speed' => 170,
                'trunk_capacity' => '14 cubic feet',
                'length' => 3995,
                'width' => 1790,
                'height' => 1642,
                'image_url' => 'https://kiavietnam.com.vn/storage/new-sonet/new-sonetjpg.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand' => 'Toyota',
                'name' => 'Corolla Cross',
                'model' => 'SUV',
                'year' => 2024,
                'engine_type' => 'Hybrid',
                'seat_capacity' => 5,
                'engine_power' => '121 HP',
                'max_speed' => 180,
                'trunk_capacity' => '14 cubic feet',
                'length' => 4460,
                'width' => 1825,
                'height' => 1620,
                'image_url' => 'https://bizweb.dktcdn.net/thumb/1024x1024/100/388/878/products/toyota-corolla-cross-2024-moi-nhat-2.png?v=1715158367267',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand' => 'Ford',
                'name' => 'Explorer',
                'model' => 'SUV',
                'year' => 2023,
                'engine_type' => 'Gasoline',
                'seat_capacity' => 7,
                'engine_power' => '300 HP',
                'max_speed' => 210,
                'trunk_capacity' => '18 cubic feet',
                'length' => 5040,
                'width' => 2004,
                'height' => 1775,
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXCajIxj-Vm4ioxXATVVyd7xWPIMmjamSt-A&s',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand' => 'Mercedes-Benz',
                'name' => 'V250',
                'model' => 'Van',
                'year' => 2024,
                'engine_type' => 'Diesel',
                'seat_capacity' => 7,
                'engine_power' => '190 HP',
                'max_speed' => 200,
                'trunk_capacity' => '25 cubic feet',
                'length' => 5140,
                'width' => 1928,
                'height' => 1880,
                'image_url' => 'https://mercedes-benz-vn.com/wp-content/uploads/v250lux.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand' => 'Hyundai',
                'name' => 'Stargazer',
                'model' => 'MPV',
                'year' => 2022,
                'engine_type' => 'Gasoline',
                'seat_capacity' => 7,
                'engine_power' => '115 HP',
                'max_speed' => 170,
                'trunk_capacity' => '20 cubic feet',
                'length' => 4460,
                'width' => 1780,
                'height' => 1690,
                'image_url' => 'https://hyundaingocan.com/wp-content/uploads/2022/10/hyundai-stargazer-2022-3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand' => 'Honda',
                'name' => 'Civic',
                'model' => 'Hatchback',
                'year' => 2024,
                'engine_type' => 'Gasoline',
                'seat_capacity' => 5,
                'engine_power' => '180 HP',
                'max_speed' => 210,
                'trunk_capacity' => '14 cubic feet',
                'length' => 4505,
                'width' => 1795,
                'height' => 1400,
                'image_url' => 'https://www.motortrend.com/uploads/sites/10/2023/09/2024-honda-civic-hatch-sport-5door-hatchback-angular-front.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand' => 'Porsche',
                'name' => '718 Boxster',
                'model' => 'Convertible',
                'year' => 2023,
                'engine_type' => 'Gasoline',
                'seat_capacity' => 2,
                'engine_power' => '300 HP',
                'max_speed' => 275,
                'trunk_capacity' => '9 cubic feet',
                'length' => 4379,
                'width' => 1801,
                'height' => 1295,
                'image_url' => 'https://porsche-vietnam.vn/wp-content/uploads/2013/11/982-718-bos-modelimage-sideshot-840x473.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand' => 'Toyota',
                'name' => 'Traveler',
                'model' => 'Van',
                'year' => 2021,
                'engine_type' => 'Diesel',
                'seat_capacity' => 9,
                'engine_power' => '150 HP',
                'max_speed' => 160,
                'trunk_capacity' => '30 cubic feet',
                'length' => 5300,
                'width' => 1920,
                'height' => 1950,
                'image_url' => 'https://hcmpeugeot.com/wp-content/uploads/2021/02/mau-xe-traveler-1.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand' => 'Mercedes-Benz',
                'name' => 'E-Class',
                'model' => 'Sedan',
                'year' => 2024,
                'engine_type' => 'Hybrid',
                'seat_capacity' => 5,
                'engine_power' => '362 HP',
                'max_speed' => 250,
                'trunk_capacity' => '13 cubic feet',
                'length' => 4923,
                'width' => 1852,
                'height' => 1460,
                'image_url' => 'https://mercedesbenz-hanoi.vn/wp-content/uploads/2024/07/e-class.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand' => 'Hyundai',
                'name' => 'Tucson',
                'model' => 'SUV',
                'year' => 2022,
                'engine_type' => 'Gasoline',
                'seat_capacity' => 5,
                'engine_power' => '187 HP',
                'max_speed' => 200,
                'trunk_capacity' => '21 cubic feet',
                'length' => 4630,
                'width' => 1865,
                'height' => 1650,
                'image_url' => 'https://hyundaitanngocan.com.vn/upload/images/Tucson/Hyundai-tucson-2022-7.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand' => 'Kia',
                'name' => 'Hybrid Crossover',
                'model' => 'SUV',
                'year' => 2023,
                'engine_type' => 'Hybrid',
                'seat_capacity' => 5,
                'engine_power' => '139 HP',
                'max_speed' => 180,
                'trunk_capacity' => '15 cubic feet',
                'length' => 4450,
                'width' => 1825,
                'height' => 1620,
                'image_url' => 'https://kiavietnam.com.vn/storage/hybrid/section4/hybrid.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand' => 'Toyota',
                'name' => 'Camry',
                'model' => 'Sedan',
                'year' => 2024,
                'engine_type' => 'Hybrid',
                'seat_capacity' => 5,
                'engine_power' => '208 HP',
                'max_speed' => 210,
                'trunk_capacity' => '15 cubic feet',
                'length' => 4885,
                'width' => 1840,
                'height' => 1445,
                'image_url' => 'https://bizweb.dktcdn.net/thumb/large/100/374/665/products/en-218-1639729011.png?v=1640169039007',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
        ]);
    }
}
