<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SalesCarsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('sales_cars')->insert([
            [
                'car_id' => 1,
                'sale_price' => 150000.00,
                'availability_status' => 'Available',
                'warranty_period' => 24,
                'sale_conditions' => 'Brand new, full warranty.',
                'quantity' => rand(1, 10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 2,
                'sale_price' => 35000.00,
                'availability_status' => 'Sold',
                'warranty_period' => 12,
                'sale_conditions' => 'Used, good condition.',
                'quantity' => rand(1, 10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 3,
                'sale_price' => 40000.00,
                'availability_status' => 'Available',
                'warranty_period' => 18,
                'sale_conditions' => 'Certified pre-owned.',
                'quantity' => rand(1, 10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 4,
                'sale_price' => 45000.00,
                'availability_status' => 'Available',
                'warranty_period' => 24,
                'sale_conditions' => 'New, limited edition.',
                'quantity' => rand(1, 10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 5,
                'sale_price' => 30000.00,
                'availability_status' => 'Sold',
                'warranty_period' => 12,
                'sale_conditions' => 'Used, excellent condition.',
                'quantity' => rand(1, 10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 6,
                'sale_price' => 32000.00,
                'availability_status' => 'Available',
                'warranty_period' => 18,
                'sale_conditions' => 'Demo car, low mileage.',
                'quantity' => rand(1, 10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 7,
                'sale_price' => 80000.00,
                'availability_status' => 'Available',
                'warranty_period' => 36,
                'sale_conditions' => 'Brand new, full options.',
                'quantity' => rand(1, 10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 8,
                'sale_price' => 35000.00,
                'availability_status' => 'Sold',
                'warranty_period' => 12,
                'sale_conditions' => 'Used, well-maintained.',
                'quantity' => rand(1, 10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 9,
                'sale_price' => 25000.00,
                'availability_status' => 'Available',
                'warranty_period' => 12,
                'sale_conditions' => 'Used, minor scratches.',
                'quantity' => rand(1, 10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 10,
                'sale_price' => 27000.00,
                'availability_status' => 'Available',
                'warranty_period' => 18,
                'sale_conditions' => 'Certified pre-owned.',
                'quantity' => rand(1, 10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 11,
                'sale_price' => 50000.00,
                'availability_status' => 'Available',
                'warranty_period' => 24,
                'sale_conditions' => 'New, special offer.',
                'quantity' => rand(1, 10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 12,
                'sale_price' => 60000.00,
                'availability_status' => 'Available',
                'warranty_period' => 36,
                'sale_conditions' => 'Brand new, full warranty.',
                'quantity' => rand(1, 10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 13,
                'sale_price' => 70000.00,
                'availability_status' => 'Sold',
                'warranty_period' => 24,
                'sale_conditions' => 'Used, excellent condition.',
                'quantity' => rand(1, 10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 14,
                'sale_price' => 80000.00,
                'availability_status' => 'Available',
                'warranty_period' => 36,
                'sale_conditions' => 'New, limited edition.',
                'quantity' => rand(1, 10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 15,
                'sale_price' => 90000.00,
                'availability_status' => 'Available',
                'warranty_period' => 24,
                'sale_conditions' => 'Brand new, full options.',
                'quantity' => rand(1, 10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 16,
                'sale_price' => 100000.00,
                'availability_status' => 'Sold',
                'warranty_period' => 36,
                'sale_conditions' => 'Used, well-maintained.',
                'quantity' => rand(1, 10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 17,
                'sale_price' => 110000.00,
                'availability_status' => 'Available',
                'warranty_period' => 24,
                'sale_conditions' => 'New, special offer.',
                'quantity' => rand(1, 10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 18,
                'sale_price' => 120000.00,
                'availability_status' => 'Available',
                'warranty_period' => 36,
                'sale_conditions' => 'Brand new, full warranty.',
                'quantity' => rand(1, 10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 19,
                'sale_price' => 130000.00,
                'availability_status' => 'Sold',
                'warranty_period' => 24,
                'sale_conditions' => 'Used, excellent condition.',
                'quantity' => rand(1, 10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 20,
                'sale_price' => 140000.00,
                'availability_status' => 'Available',
                'warranty_period' => 36,
                'sale_conditions' => 'New, exclusive offer.',
                'quantity' => rand(1, 10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
